### ISSUE TITLE
plugin not a function

### ISSUE THREAD

**Issue by Ruegen** [fabiospampinato/mongoose-findoneorcreate#1]
I get ```throw new Error('First param to `schema.plugin()` must be a function, ' +```

Not sure as to why - checked your code and it seems to be a function?

**Comment by fabiospampinato** [comment]
Have you tried putting a `debugger` statement in your program and see what's actually going wrong?

**Comment by Ruegen** [comment]
line 23 of index.js has 
```
/* EXPORT */
exports.default = findOneOrCreate;
```

I changed it to 
```
module.exports = findOneOrCreate;
```
and it works fine

**Comment by fabiospampinato** [comment]
Right, I did develop this as a TypeScript package, in that language it's common to export the main function as the "default" export. In order to use it on a plain Node file you should import it as:

`const {default: findOneOrCreate} = require ( 'mongoose-findoneorcreate' )`

**Comment by Ruegen** [comment]
many thanks - that worked fine. Will note that whenever I deal with a package built with typescript.
